client_config_backend: settings
client_config:
  client_id: 763706615163-71dtvkrc27q7gvaueqvo0d792ge2flm9.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file